CUDA_VISIBLE_DEVICES=0 nohup python main_calibration_a.py --model /workspace/volume/inference-soft-data/AE/llm/models/llama-7b-hf --epochs 20 --output_dir ./log-calibration-compensation-lwc-rank/llama-7b-hf-w4a4-2 --eval_ppl --wbits 4 --abits 4 --let --lwc --tasks piqa,arc_easy,arc_challenge,boolq,hellaswag,winogrande --compensation_calibration --rank 2 > ./log-calibration-compensation-lwc-rank/llama-7b-hf-w4a4-2.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python main_calibration_a.py --model /workspace/volume/inference-soft-data/AE/llm/models/llama-7b-hf --epochs 20 --output_dir ./log-calibration-compensation-lwc-rank/llama-7b-hf-w4a4-4 --eval_ppl --wbits 4 --abits 4 --let --lwc --tasks piqa,arc_easy,arc_challenge,boolq,hellaswag,winogrande --compensation_calibration --rank 4 > ./log-calibration-compensation-lwc-rank/llama-7b-hf-w4a4-4.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup python main_calibration_a.py --model /workspace/volume/inference-soft-data/AE/llm/models/llama-7b-hf --epochs 20 --output_dir ./log-calibration-compensation-lwc-rank/llama-7b-hf-w4a4-8 --eval_ppl --wbits 4 --abits 4 --let --lwc --tasks piqa,arc_easy,arc_challenge,boolq,hellaswag,winogrande --compensation_calibration --rank 8 > ./log-calibration-compensation-lwc-rank/llama-7b-hf-w4a4-8.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup python main_calibration_a.py --model /workspace/volume/inference-soft-data/AE/llm/models/llama-7b-hf --epochs 20 --output_dir ./log-calibration-compensation-lwc-rank/llama-7b-hf-w4a4-16 --eval_ppl --wbits 4 --abits 4 --let --lwc --tasks piqa,arc_easy,arc_challenge,boolq,hellaswag,winogrande --compensation_calibration --rank 16 > ./log-calibration-compensation-lwc-rank/llama-7b-hf-w4a4-16.log 2>&1 &

CUDA_VISIBLE_DEVICES=4 nohup python main_calibration_a.py --model /workspace/volume/inference-soft-data/AE/llm/models/llama-13b-hf --epochs 20 --output_dir ./log-calibration-compensation-lwc-rank/llama-13b-hf-w4a4-2 --eval_ppl --wbits 4 --abits 4 --let --lwc --tasks piqa,arc_easy,arc_challenge,boolq,hellaswag,winogrande --compensation_calibration --rank 2  > ./log-calibration-compensation-lwc-rank/llama-13b-hf-w4a4-2.log 2>&1 &
CUDA_VISIBLE_DEVICES=5 nohup python main_calibration_a.py --model /workspace/volume/inference-soft-data/AE/llm/models/llama-13b-hf --epochs 20 --output_dir ./log-calibration-compensation-lwc-rank/llama-13b-hf-w4a4-4 --eval_ppl --wbits 4 --abits 4 --let --lwc --tasks piqa,arc_easy,arc_challenge,boolq,hellaswag,winogrande --compensation_calibration --rank 4  > ./log-calibration-compensation-lwc-rank/llama-13b-hf-w4a4-4.log 2>&1 &
CUDA_VISIBLE_DEVICES=6 nohup python main_calibration_a.py --model /workspace/volume/inference-soft-data/AE/llm/models/llama-13b-hf --epochs 20 --output_dir ./log-calibration-compensation-lwc-rank/llama-13b-hf-w4a4-8 --eval_ppl --wbits 4 --abits 4 --let --lwc --tasks piqa,arc_easy,arc_challenge,boolq,hellaswag,winogrande --compensation_calibration --rank 8  > ./log-calibration-compensation-lwc-rank/llama-13b-hf-w4a4-8.log 2>&1 &
CUDA_VISIBLE_DEVICES=7 nohup python main_calibration_a.py --model /workspace/volume/inference-soft-data/AE/llm/models/llama-13b-hf --epochs 20 --output_dir ./log-calibration-compensation-lwc-rank/llama-13b-hf-w4a4-16 --eval_ppl --wbits 4 --abits 4 --let --lwc --tasks piqa,arc_easy,arc_challenge,boolq,hellaswag,winogrande --compensation_calibration --rank 16  > ./log-calibration-compensation-lwc-rank/llama-13b-hf-w4a4-16.log 2>&1 &
